## Thread support
if(WIN32)
  set(CMAKE_THREAD_PREFER_PTHREAD OFF)
  include(FindThreads)
  if(NOT CMAKE_USE_WIN32_THREADS_INIT)
    message(FATAL_ERROR "Win32 Thread is required")
  endif(NOT CMAKE_USE_WIN32_THREADS_INIT)
  link_libraries(${CMAKE_THREAD_LIBS_INIT})
endif()

if(NOT APPLE AND NOT WIN32)
  if (ANDROID)
    set(THREADS_HAVE_PTHREAD_ARG true)
  endif()
  set(CMAKE_THREAD_PREFER_PTHREAD ON)
  include(FindThreads)
  if(NOT CMAKE_USE_PTHREADS_INIT)
    message(FATAL_ERROR "Pthread is required")
  endif(NOT CMAKE_USE_PTHREADS_INIT)
  link_libraries(${CMAKE_THREAD_LIBS_INIT})
endif()

if(APPLE)
  message(STATUS "Found Threads: APPLE")
endif()
